name: Build and Push Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: trevorsharp/youtube-podcast-feeds
        tags: latest
