name: Build and Push Docker
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: trevorsharp/youtube-podcast-feeds
          tags: latest
      - uses: actions/checkout@v2
      - name: Build and Push Docker Image (Downloader)
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          path: ./downloader
          repository: trevorsharp/youtube-podcast-feeds-downloader
          tags: latest
